### ISSUE TITLE
Highlight a button to get to the API / File URLs

### ISSUE THREAD

**Issue by Echolon** [xsf/xmpp-providers-website#37]
I could think of the head bar. Its always present not to loaded and we could place a link, like we do to xmpp.work on xmpp.org

**Comment by Echolon** [comment]
https://github.com/xsf/mediawiki-docker/pull/9

**Comment by melvo** [comment]
I suggest to not simply link to the file URLs for a whole category from the website because it could lead to misunderstanding. The XMPP Providers repository is linked from multiple locations on the website and should help to understand what the files are and how they are used. Links from the provider details to specific lines in the source file could be useful for providers to improve their category, though.

**Comment by wurstsalat3000** [comment]
Added in 16220acb280593dbd0be3f6f07d7c8c40a7cb660
