### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by wurstsalat3000** [xsf/xmpp-providers-website#4]
### Website

* [x] add license (https://reuse.software) ?
* [x] check logo license
* [x] alphabetical sorting of providers in overview (category first, then alphabetical)
* [x] Implement list of client with XMPP providers integration ("Integration" menu item)
* [x] unify colors of categories/badges
* [x] separate language links by comma
* [x] add favicon
* [x] hover effect for rating badges
* [x] add more space to Details button in overview
* [x] add shortcode for `target="_blank"` links in markdown files (to open them in a new tab)
* [x] check horizontal alignment of icons in details view
* [x] summarize support addresses requirement (1 is required, don't list every missing address)
* [x] "Server location:" use plural
* [x] copy button for badge code (needs JS)
* [x] live filtering of results using JS

**Comment by melvo** [comment]
@wurstsalat3000 Thanks for this overview. Here are some minor issues:

- [ ] *Read more about how categories are determined.* should link to https://invent.kde.org/melvo/xmpp-providers/-/blob/master/README.md#categories
- [ ] *Compatibility / Security* should be used on the overview page instead of *Compatibility*
